export default function ColorMap(str) {
    const color = ["#5470c6",
        "#91cc75",
        "#fac858",
        "#ee6666",
        "#73c0de",
        "#3ba272",
        "#fc8452",
        "#9a60b4",
        "#ea7ccc"];
    const themes = [
        "interactive",
        "visualizing",
        "coordinated multiple views",
        "stream",
        "model",
        "analytics",
        "coordinated and multiple views",
        "treemaps",
        "virtual environments",
        "network layout",
        "visualization",
        "scientific visualization",
        "text analytics",
        "classification",
        "dimensional",
        "multivariate data",
        "design space",
        "text visualization",
        "system",
        "visual knowledge discovery",
        "texture mapping",
        "systems",
        "virtual reality",
        "multivariate visualization",
        "education",
        "geometric",
        "multidimensional scaling",
        "time series data",
        "framework",
        "ensemble visualization",
        "visual analysis",
        "geovisualization",
        "design study",
        "flow",
        "multivariate",
        "clustering",
        "dimensionality reduction",
        "high-dimensional data",
        "deep learning",
        "parallel coordinates",
        "segmentation",
        "interactive visual analysis",
        "direct manipulation",
        "interactive visualization",
        "neural networks",
        "feature detection",
        "graph visualization",
        "data transformation",
        "level-of-detail",
        "algorithm",
        "graphics hardware",
        "volume visualization",
        "evaluation",
        "volume rendering",
        "image",
        "visual analytics",
        "interaction techniques",
        "graphical perception",
        "exploratory data analysis",
        "optimization",
        "uncertainty visualization",
        "design studies",
        "focus+context visualization",
        "techniques",
        "immersive analytics",
        "topological data analysis",
        "network visualization",
        "information visualization",
        "treamline'",
        "multidimensional data",
        "interaction",
        "medical visualization",
        "rendering",
        "flow visualization",
        "dynamic visualization",
        "focus+context",
        "graph layout",
        "interactive exploration",
        "data mining",
        "3d",
        "collaboration",
        "web-based visualization",
        "principal component analysis",
        "graphics",
        "time-varying data visualization",
        "machine learning",
        "information",
        "multidimensional visualization",
        "bioinformatics visualization",
        "illustrative visualization",
        "streamlines",
        "others",
        "isosurface extraction",
        "marching cubes",
        "perception",
        "visual knowledge representation",
        "scatterplot",
        "",
        "Re: Domande per Chaouki",
        "[!GAC-619-29156]: Request for exploits",
        "prova",
        "Re: [Fwd: domanda di lavoro]",
        "R: Errore TNI - Fake Access Point",
        "Re: [Fwd: Re: Richiesta informazioni]",
        "RE: VMWare",
        "test",
        "[!QMG-419-93914]: RCS 9.5 Mono db upgrade Error !!",
        "[!ILH-271-32685]: Error synchronizing",
        "R: Antenne",
        "TODO",
        "R: Richiesta Antenne",
        "R: Vittoria Liberatoria",
        "Re: Sull'upgrade delle backdoor",
        "R: Abi  con domande",
        "Re: Pendrive con autorun",
        "R: ORDINE - COMMESSE INTERNE HT",
        "[!XYU-799-99817]: RCS NIA",
        "Re: Richiesta informazioni",
        "R: New member on board",
        "Re: training Ungheria MKIH",
        "Re: Mac Malware Spies On Email, Survives Reboots",
        "Re: Exploits have been patched",
        "[VTMIS][d3e866e5bf18f2d9c667563de9150b705813e03377312b6974923f6af2e56291] sample",
        "R: Management Remoto TNI",
        "[!JFN-242-30736]: Modulo chat Skype 7.5",
        "Re: sar\u00e0 sicuro?",
        "Re: attivit\u00e0 aggiornamento e training Postale",
        "Attivita` CollaboratoriOnline",
        "[!ZYI-251-55279]: shard service",
        "Re: Legal Trojan",
        "Re: Osx Crisis/morcut",
        "ciao",
        "R: Royal PT e F5",
        "Re: sul corriere...",
        "Re: domande tecniche RCS/VOIP",
        "R: Re: Penetration Test SIS",
        "Re: Un po' in anticipo..",
        "R: Re: Progetto db masking per Barclays",
        "Re: R: Sviluppi non viewer-related",
        "Re: Problemi con l'invio di posta dall'esterno",
        "Re: R: interpretazione",
        "Re: sicurezza infrastruttura bes",
        "Re: VUPEN / Code Update",
        "R: e bravo naif.....",
        "Re: Planning 2006",
        "Re: Collector da disabilitare",
        "R: Incontro Vittoria",
        "R: Re: URGENTE: merda secca!!",
        "Re: RCS testing",
        "Re: Aladdin sotto linux",
        "Re: I: MySQL License",
        "Re: Credenziali CheckIn/CheckOut",
        "Re: Pranzo gioved\u00ec",
        "[BULK]  Voglio offrirvi un'opportunita di lavoro con holding operante a livello globale.",
        "R: Tni Nia Telecom Italia",
        "Re: Hackers release browser-based 'jailbreak' for iPhone 4",
        "bin",
        "Re: I: I: Punti patente DA DIVULGARE",
        "Re: WebInspect 7",
        "Re: build error",
        "RE: Sony BMG to compensate buyers of flawed CDs",
        "[!UQN-139-35526]: Exploit web Android",
        "[!YMN-265-89975]: Cannot apply conf to anons !",
        "R: Attivita' di EH",
        "Re: I: POESIA",
        "[!WLB-866-72418]: Inquire ",
        "R: TNI help me",
        "Re: R: Test nuovo SIS v5.0",
        "[!OEY-135-84265]: Acceso a servidor",
        "Re: URGENTE: merda secca!!",
        "Re: Forno a microonde",
        "Re: Meet \u201cbadBIOS,\u201d the mysterious Mac and PC malware that jumps airgaps",
        "[!PQQ-100-46911]: collector queue",
        "Re: AVG Anti-Rootkit Free",
        "Re: Proposte di colloquio",
        "R: RSA VA-PT retest SIS 5.0",
        "Re: infection CD spain",
        "R: Conferma risultati",
        "Re: contro-analisi di kaspersky...",
        "Re: in effetti...",
        "[!WUD-894-39291]: Android Exploit 18/12/14",
        "Re: nuova conf",
        "R: Info",
        "[!LLA-775-12733]: Browser klogger not working",
        "R: Re: Osx Crisis/morcut",
        "Re: FW: Curriculum Vitae",
        "Re: exploit word",
        "[!KNZ-947-47808]: EXE installator out of order",
        "R: Commessa Lispa",
        "[!HNI-103-39412]: Login Failure",
        "R: hacking tool",
        "[!QSX-223-43223]: The evidence did not received",
        "Re: Atlas restarting, ID: Atlas HackingTeam-INC-2012/0004",
        "Re: Riunione Difensiva"


    ];
    const index = themes.indexOf(str) + 1
    return color[index % color.length]
}